[package]
name = "pm-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pm-protocol = { workspace = true }
pm-client = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
