// Bundles the xterm.js WebView mini-app into one self-contained HTML file
// and a generated TS module the React Native shell embeds. Run through
// `pnpm -F puppet-master-mobile run build:terminal`.
import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

let result;
try {
  result = await build({
    entryPoints: [join(root, "src", "main.ts")],
    bundle: true,
    format: "iife",
    minify: true,
    write: false,
    target: ["safari17"],
    legalComments: "none",
    tsconfig: join(root, "tsconfig.json"),
    alias: {
      "@puppet-master/client-core": join(root, "..", "..", "..", "packages", "client-core", "src"),
    },
  });
} catch (error) {
  if (error && Array.isArray(error.errors)) {
    for (const err of error.errors) {
      const loc = err.location ? `${err.location.file}:${err.location.line}:${err.location.column}: ` : "";
      process.stderr.write(`${loc}error: ${err.text}\n`);
    }
  }
  throw error;
}

const js = result.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const css = readFileSync(require.resolve("@xterm/xterm/css/xterm.css"), "utf8");
const template = readFileSync(join(root, "index.html"), "utf8");
const html = template.replace("__XTERM_CSS__", () => css).replace("__BUNDLE_JS__", () => js);

const distDir = join(root, "dist");
mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, "terminal.html"), html);

const genDir = join(root, "..", "src", "terminal", "gen");
mkdirSync(genDir, { recursive: true });
const banner = "// Generated by terminal-web/build.mjs. Do not edit.\n";
writeFileSync(
  join(genDir, "terminalHtml.ts"),
  `${banner}export const terminalHtml: string = ${JSON.stringify(html)};\n`,
);

console.log(`terminal.html ${(html.length / 1024).toFixed(0)} KiB`);
